	var __wxAppData = {}; 	var __wxRoute; 	var __wxRouteBegin; 	var global = {}; 		define("utils/util.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 !function(){"use strict";function t(t){var n=t.getFullYear(),o=t.getMonth()+1,r=t.getDate(),u=t.getHours(),i=t.getMinutes(),g=t.getSeconds();return[n,o,r].map(e).join("/")+" "+[u,i,g].map(e).join(":")}function e(t){return t=t.toString(),t[1]?t:"0"+t}module.exports={formatTime:t}}(); 
 			}); 		define("app.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 !function(){"use strict";App({onLaunch:function(){var n=wx.getStorageSync("logs")||[];n.unshift(Date.now()),wx.setStorageSync("logs",n)},getUserInfo:function(n){var o=this;this.globalData.userInfo?"function"==typeof n&&n(this.globalData.userInfo):wx.login({success:function(t){wx.getUserInfo({success:function(t){o.globalData.userInfo=t.userInfo,"function"==typeof n&&n(o.globalData.userInfo)}})}})},globalData:{url:"https://www.hfzfkj.cn",userInfo:null}})}(); 
 			}); 	require("app.js");
 		__wxRoute = 'pages/login/login';__wxRouteBegin = true; 	define("pages/login/login.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 !function(){"use strict";var e="",o=0,s="",a=getApp();Page({data:{motto:"欢迎您",userInfo:{},dwmc:"",openid:"",session_key:"",disabled:!1,userName:"",userPassword:""},onLoad:function(o){console.log("onLoad"),console.log(a.globalData);var n=this,t=wx.getStorageSync("userName"),r=wx.getStorageSync("userPassword");console.log(t),console.log(r),t&&this.setData({userName:t}),r&&this.setData({userPassword:r}),wx.login({success:function(o){wx.getUserInfo({success:function(e){n.setData({userInfo:e.userInfo}),s=e.userInfo.nickName,console.log(s)}}),wx.request({url:a.globalData.url+"/sxxm/servlet/getOpenid",data:{appid:"wx0bf0a846227e4743",secret:"39cf6f77a0c9bf5bff09aca3ad4e65fa",js_code:o.code,grant_type:"authorization_code"},method:"GET",success:function(o){console.log(o.data),e=o.data.openid,console.log(e.length),n.setData({openid:o.data.openid,session_key:o.data.session_key})}})}})},formSubmit:function(n){console.log(n.detail.value);var t=n.detail.value,r=this;t.userName&&t.userPassword&&(wx.setStorageSync("userName",t.userName),wx.setStorageSync("userPassword",t.userPassword),wx.request({url:a.globalData.url+"/sxxm/servlet/userLogin",data:{username:t.userName,password:t.userPassword,openid:e,nickname:s},method:"GET",success:function(s){o=s.data.rec,1==o?wx.navigateTo({url:"../index/index?openid="+e}):r.setData({info:"用户名或密码错误"})}}))},onReady:function(){},onShow:function(){},onHide:function(){},onUnload:function(){}})}(); 
 			}); 	require("pages/login/login.js");
 		__wxRoute = 'pages/index/index';__wxRouteBegin = true; 	define("pages/index/index.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 !function(){"use strict";var o=getApp(),d="",a=0,n=0,e="";Page({data:{motto:"欢迎您",userInfo:{},dwmc:"",disabled:!1},bindViewTap:function(){wx.navigateTo({url:"../logs/logs"})},onLoad:function(c){console.log("onLoad");var s=this;console.log("跳转带过来的参数"+c.openid),e=c.openid,o.getUserInfo(function(o){s.setData({userInfo:o})}),wx.login({success:function(c){c.code?wx.request({url:o.globalData.url+"/sxxm/servlet/login?",data:{openid:e},method:"GET",success:function(o){o.data.dwmc,s.setData({dwmc:o.data.dwmc,disabled:!1}),d=o.data.dwmc,a=o.data.dwid,n=o.data.lxrid}}):console.log("获取用户登录态失败！"+res.errMsg)}})},btn_kccx:function(o){console.log("../scan-code/scan-code?dwmc="+d+"&dwid"+a+"&lxrid"+n),wx.navigateTo({url:"../scan-code/scan-code?dwmc="+d+"&dwid_s="+a+"&lxrid_s="+n})}})}(); 
 			}); 	require("pages/index/index.js");
 		__wxRoute = 'pages/logs/logs';__wxRouteBegin = true; 	define("pages/logs/logs.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 !function(){"use strict";var t=require("../../utils/util.js");Page({data:{logs:[]},onLoad:function(){this.setData({logs:(wx.getStorageSync("logs")||[]).map(function(a){return t.formatTime(new Date(a))})})}})}(); 
 			}); 	require("pages/logs/logs.js");
 		__wxRoute = 'pages/scan-code/scan-code';__wxRouteBegin = true; 	define("pages/scan-code/scan-code.js", function(require, module, exports, window,document,frames,self,location,navigator,localStorage,history,Caches,screen,alert,confirm,prompt,XMLHttpRequest,WebSocket,Reporter,webkit,WeixinJSCore){ 			
 !function(){"use strict";var s=0,a=0,t=getApp();Page({onLoad:function(t){getApp();console.log("跳转带过来的参数"+t.dwmc),wx.setNavigationBarTitle({title:t.dwmc,success:function(s){}}),s=t.dwid_s,a=t.lxrid_s},data:{result:"",barcode:"",sptm:"",spmc:"",spgg:"",sccj:"",kcshl:""},bindfocus:function(s){this.setData({barcode:""}),console.log(barcode)},scanCode:function(){var c=this,o="";console.log("2222222333333"),wx.scanCode({success:function(e){o=e.result,console.log("444444"),console.log(o),wx.request({url:t.globalData.url+"/sxxm/servlet/wms_kccx?",data:{sptm:o,dwid:s,lxrid:a},method:"GET",success:function(s){c.setData({sptm:"商品条码："+s.data.sptm,spmc:s.data.spmc,spgg:s.data.spgg,sccj:s.data.sccj,kcshl:s.data.kcshl,jwh:s.data.jwh})}})},fail:function(s){}})},search:function(c){var o=this,e="";this.setData({barcode:c.detail.value}),console.log("2222222333333"),e=o.data.barcode,console.log("444444"),console.log(e),wx.request({url:t.globalData.url+"/sxxm/servlet/wms_kccx?",data:{sptm:e,dwid:s,lxrid:a},method:"GET",success:function(s){o.setData({sptm:s.data.sptm,spmc:s.data.spmc,spgg:s.data.spgg,sccj:s.data.sccj,kcshl:s.data.kcshl,jwh:s.data.jwh})}})}})}(); 
 			}); 	require("pages/scan-code/scan-code.js");
 	